config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'


  get 'about' => 'pages#about'

  resources :posts do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true,
                   length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end




    private def comment_params
            params.require(:comment).permit(:username, :body)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
         @title = 'Welcome to Gaslight Estates';
         @content = 'Inportant information about Gaslite Estates';
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except:[:index, :show]
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end 
    
    def new 
        @post = Post.new
    end
    
    def create
        
        @post = Post.new(post_params)

        if(@post.save)
            redirect_to @post
        else
            render 'new' 
        end   
    end

    def edit
       @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit' 
        end   
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end

    private def post_params
       params.require(:post).permit(:title, :body)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
   <div class="p-3 mb-2 bg-light text-dark border rounded">
   <p><strong><%= comment.username %></strong> : <%= comment.body %></p>         
   <% if user_signed_in? %> 
   <%= link_to "Delete comment", [comment.post, comment],
        method: :delete,
        data:{confirm: 'Are you sure you want to DELETE?'},
        :class => 'badge badge-danger' %>
      <% end %>
        </div>
    <% end %>

    <hr>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>

<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
         <%= f.label :username %><br>
         <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p> 
 
    <p>
       <%= f.label :body %><br>
       <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
 
    <p>
       <%= f.submit({:class => 'btn btn-outline-success'}) %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neighborsblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- This menu bar will show in every html.erb page -->
  <nav class="navbar navbar-expand-md navbar navbar-light fixed-top" style="background-color: #28a745;">
  <a class="navbar-brand"<%= link_to "Gaslite States", about_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon dropdown"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">
       <a class= "nav-link"<%= link_to "Post Page", home_path %></a>
      </li>
      <li class="nav-item active">
       <a class= "nav-link"<%= link_to "Add Post", new_post_path %></a>
      </li>
    </ul>
  </div>
</nav>
<hr>
<hr>

<div class="container"

</div>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  <!-- small footer with copy right -->
  <footer>
     <div class="card bg-success" style="background-color: #28a745, high: 4px;"><br> 
        <p class="text-center ">@copy right 2019 </p>
    </div>
  </footer>
  
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</html>

app/views/pages/about.html.erb
<!-- thi is where the carousel start with boostrap -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
    <img class="card-img " <%= image_tag "GL Banner.jpg" %> 
    </div>
    <div class="carousel-item">
    <img class="card-img " <%= image_tag "GL Banner1.jpg" %> 
    </div>
    <div class="carousel-item">
    <img class="card-img " <%= image_tag "GL Logo.jpg" %> 
    </div>
  </div>
  
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<hr>
<h1><%= @title %></h1>
<p><%= @content %></p>
<hr>
<div class="card border-success mb-3" style="max-width: 1500px;">
  <div class="row no-gutters">
    <div class="col-md-8">
      <div class="card-body text-success text-center">
        <h4 class="card-title">Thanks to all that attended the Annual Meeting</h4>
        <p class="card-text">Hope to see you in our next meeting, get involved.</p>
        <p class="card-text"><small class="text-muted">next meeting 01/20/2020</small></p>
      </div>
    </div>
    <div class="col-md-4">
      <img class="card-img " <%= image_tag "GL Attending.jpg" %> 
    </div>
  </div>
</div>
<hr>
<div class="card border-success mb-3" style="max-width: 1500px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img class="card-img" <%= image_tag "GL Board members.jpg" %> 
    </div>
    <div class="col-md-8">
      <div class="card-body text-success text-center float-left">
        <h4 class="card-title">Current Board members for Gaslite Estates </h4>
        <p class="card-text">WILLIAM EARP	- SUPPORTING <br> JAMES HOWARD	- SUPPORTING <br> KEITH HENDERSON - VP/SECRETARY <br> JAMES PARKER	- PRESIDENT/TREASURER</p>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card border-success mb-3" style="max-width: 1500px;">
  <div class="row no-gutters">
    <div class="col-md-8">
      <div class="card-body text-success text-center">
        <h4 class="card-title">Handy Numbers to know.</h4>
        <a href="tel:502-555-5555"><i class="fas fa-phone"></i> J-Town Mayor Bill Dieruf: (502)266-5000</a><br>
        <a href="tel:502-555-5555"><i class="fas fa-phone"></i> J-Town Police Department : (502)267-0503</a><br>
        <a href="tel:502-555-5555"><i class="fas fa-phone"></i> J-Town Fire Station 3 : (502)491-7300</a><br>
        <a href="tel:502-555-5555"><i class="fas fa-phone"></i> Report Street Light Outage : (502)589-1444</a><br>
      </div>
    </div>
    <div class="col-md-4">
      <img class="card-img " <%= image_tag "GL Phones.jpg" %> 
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> Edit Your Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
   <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
         <div class= "alert alert-danger"><%= msg %></div>
         <% end %>
   <% end %> 
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
   </p> 

   <p>
      <%= f.label :body %><br>
      <%= f.text_area(:body, {:class => 'form-control'}) %>
   </p>

   <p>
      <%= f.submit({:class => 'btn btn-outline-success'}) %>
   </p>
 <% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
    <div class="p-3 mb-2 bg-light text-dark border rounded">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <p><%= post.created_at.strftime("%B, %d, %Y") %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-outline-success' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1> Add New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
       <% @post.errors.full_messages.each do |msg| %>
          <div class= "alert alert-danger"><%= msg %></div>
          <% end %>
    <% end %> 
     <p>
         <%= f.label :title %><br>
         <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p> 
 
    <p>
       <%= f.label :body %><br>
       <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
 
    <p>
       <%= f.submit({:class => 'btn btn-outline-success'}) %>
    </p>
  <% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<p>Submitted <%= time_ago_in_words(@post.created_at) %> Ago</p>
<% if user_signed_in? %> 
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-outline-success' %>
<%= link_to "Delete", post_path(@post), 
                method: :delete,
                data: {confirm: 'Are you sure you want to DELETE your post?'},
                :class => 'btn btn-danger' %>
    <% end %>            

<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>